// articles
export const ACTION_GET_LIST_ARTICLES = 'ACTION_GET_LIST_ARTICLES';
export const ERROR_GET_LIST_ARTICLES = 'ERROR_GET_LIST_ARTICLES';

export const ACTION_CREATED_NEW_POST = 'ACTION_CREATED_NEW_POST';
export const ERROR_CREATED_NEW_POST = 'ERROR_CREATED_NEW_POST';

// users
export const SET_USER_EMAIL = 'SET_USER_EMAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const GET_USER_WITH_ID_SUCCESS = 'GET_USER_WITH_ID_SUCCESS';
export const GET_USER_WITH_ID_FAILED = 'GET_USER_WITH_ID_FAILED'

export default {
	// articles
	ACTION_GET_LIST_ARTICLES,
	ERROR_GET_LIST_ARTICLES,

	ACTION_CREATED_NEW_POST,
	ERROR_CREATED_NEW_POST,

	// users
	SET_USER_EMAIL,
	LOGIN_SUCCESS,
	LOGIN_FAILED,
	SIGNUP_SUCCESS,
	SIGNUP_FAILED,
	GET_USER_WITH_ID_SUCCESS,
	GET_USER_WITH_ID_FAILED,
};
